### ISSUE TITLE
Broken code

### ISSUE THREAD

**Issue by Zaldor** [dkl3/py-issuu-scrape#4]
URLIB has some function deprecated and
on entering url:

> Enter the url: https://issuu.com/(whatever)
> Traceback (most recent call last):
>   File "./issuu.py", line 10, in <module>
>     x = str(input("Enter the url: "))
>   File "<string>", line 1
>     https://issuu.com/(whatever)
>           ^
> SyntaxError: invalid syntax

**Comment by jpeacock29** [comment]
Is this the error exactly as it appeared? Line 1 of the script is `from bs4 import BeautifulSoup`, so it's a bit confusing.
